Fix undefined `site.data["author"].each` on sites without `authors.yml`
Upstream docs clearly state that since Jekyll 4.3.0, themes can
include `_data` and that this data will be available to consuming
project (unless overridden).
https://jekyllrb.com/docs/themes/#themes-with-data-directory

However, reality disagrees with this. In qunitjs/qunit, where
there is no _data/authors.yml file, using the latest version of this
gem-based theme, fails as follows:

```
undefined method `each' for false (NoMethodError)
			site.data["authors"].each do |slug, name|

from /opt/homebrew/lib/ruby/gems/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:193:in `block in generate'
…
from /opt/homebrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
…
from /opt/homebrew/lib/ruby/gems/3.2.0/bin/bundle:25:in `<main>'
```